#!/usr/bin/env bash
# What an answer file can do to the installer that reads it.
#
# `--answers FILE` is the one input to this installer that is a file rather
# than a person: written by hand, copied between machines, pasted into a chat
# and edited on the way, generated by somebody's script. Every other test of it
# feeds it well formed lines and checks the answers come back. This one feeds
# it the shapes a text file actually arrives in and checks the installer is
# still running afterwards.
#
# It found six things, and two of them ended the installer before it drew a
# screen:
#
#   A line beginning with `=` reached an associative array as an empty
#   subscript, which is fatal under `set -u`, from a file the user had merely
#   mistyped.
#
#   `--answers /mnt/usb` instead of `--answers /mnt/usb/answers` passed the
#   `-r` test on a directory, and `read` then failed without ever assigning the
#   variable the loop condition reads.
#
#   A key name went from the file onto the review screen with its control
#   characters intact, so a file could clear or repaint the last screen before
#   the erase gate.
#
#   A UTF-8 byte order mark, which is what an editor on Windows writes when it
#   is asked for UTF-8, made the first answer silently not an answer, and the
#   name reported back looked identical to the real one.
#
#   Every space in a key name was deleted rather than the surrounding ones, so
#   `t a r g e t=/dev/sda` set the disk to erase.
#
#   The list of names the file got wrong was unbounded in both length and
#   count, and both of those reach a screen.
set -Eeuo pipefail
trap 'case $- in *e*) printf "%s: line %s gave up: %s\n" "${0##*/}" "$LINENO" "$BASH_COMMAND" >&2 ;; esac' ERR
# shellcheck source=assert.sh
. "$(dirname -- "$0")/assert.sh"

ROOT=$(cd -- "$(dirname -- "$0")/../.." && pwd -P)
export AURADE_TUI_COLUMNS=68

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

fail() { echo "test-answers-fuzz: $*" >&2; exit 1; }

install -d "$TMP/zoneinfo" "$TMP/locales" "$TMP/keymaps/i386/qwerty" \
  "$TMP/block/sda" "$TMP/dri" "$TMP/bundle"
: >"$TMP/zoneinfo/UTC"; : >"$TMP/locales/en_US"
: >"$TMP/keymaps/i386/qwerty/us.map.gz"
printf '%s\n' '2026/07/12' >"$TMP/snapshot"
printf 'MemAvailable:   16000000 kB\n' >"$TMP/meminfo"
printf '%s\n' '/dev/sda|931.5G|WDC WD10EZEX|sata|WD-WCC6Y4KP1234' >"$TMP/disks"
export AURADE_ZONEINFO_DIR="$TMP/zoneinfo" AURADE_LOCALE_DIR="$TMP/locales"
export AURADE_KEYMAP_DIR="$TMP/keymaps" AURADE_BLOCK_DIR="$TMP/block"
export AURADE_SNAPSHOT_FILE="$TMP/snapshot" AURADE_DISK_TABLE="$TMP/disks"
export AURADE_PROBE_MEMINFO="$TMP/meminfo" AURADE_PROBE_DRI_DIR="$TMP/dri"
export AURADE_TUI_COLOR=none AURADE_TUI_FRAME=ascii
export AURADE_BUNDLE_DIR="$TMP/bundle"
export AURADE_REPO_FINGERPRINT_FILE="$TMP/repo-fingerprint"
export AURADE_INSTALLER_TUI_LIB=1
# shellcheck source=../bin/aurade-installer-tui
. "$ROOT/installer/bin/aurade-installer-tui"

# Load a file and hand back the outcome without the caller's shell dying with
# it. The whole point of this file is inputs that used to kill the process, so
# every load runs in a subshell under the same `set -Eeuo pipefail` the front
# end runs under, and the exit status distinguishes "refused" from "died".
#
# 0  the file was read
# 1  the file was refused, which is a normal answer
# 2+ the loader crashed, which is the bug this file is about
load() {
  local file=$1 rc=0
  ( set -Eeuo pipefail
    ANSWERS=(); ANSWERS_REJECTED=(); ANSWERS_REJECTED_MORE=0
    answers_load "$file" ) >"$TMP/load.out" 2>"$TMP/load.err" || rc=$?
  return "$rc"
}

# The same, in this shell, for the cases that are about what came back.
loaded() {
  ANSWERS=(); ANSWERS_REJECTED=(); ANSWERS_REJECTED_MORE=0
  answers_load "$1"
}

survives() {
  local what=$1 file=$2 rc=0
  load "$file" || rc=$?
  (( rc <= 1 )) || {
    printf 'test-answers-fuzz: %s killed the loader (exit %s)\n' "$what" "$rc" >&2
    sed 's/^/    /' "$TMP/load.err" >&2
    exit 1
  }
}

# --- lines that are not lines ------------------------------------------------
#
# Each of these is one hand-editing mistake away from a file this installer
# wrote itself, so none of them may be fatal and none of them may be believed.

printf '%s\n' '=/dev/sda' >"$TMP/no-name"
survives 'a line with no name' "$TMP/no-name"
loaded "$TMP/no-name"
[[ -z ${ANSWERS[target]:-} ]] || fail 'a nameless line set an answer'
# And it is skipped rather than counted. A line with nothing to the left of the
# equals sign never named a question, so counting it towards "and 3 more" sends
# somebody looking through the file for three questions it does not contain.
(( ANSWERS_REJECTED_MORE == 0 )) ||
  fail 'a line with no name was counted as a question that was refused'

printf '%s\n' '   =/dev/sda' >"$TMP/space-name"
survives 'a line whose name is only spaces' "$TMP/space-name"
loaded "$TMP/space-name"
(( ANSWERS_REJECTED_MORE == 0 )) ||
  fail 'a line whose name is only spaces was counted as a question that was refused'

printf '%s\n' 'target' 'hostname' '' '   ' '#target=/dev/sda' >"$TMP/no-equals"
survives 'lines with no equals sign' "$TMP/no-equals"
loaded "$TMP/no-equals"
[[ -z ${ANSWERS[target]:-} ]] || fail 'a commented line set an answer'
(( ${#ANSWERS_REJECTED[@]} == 0 )) ||
  fail "lines that are not answers were reported as refused answers: ${ANSWERS_REJECTED[*]}"

printf 'hostname=aurade' >"$TMP/no-newline"
loaded "$TMP/no-newline" || fail 'a file with no trailing newline was refused'
[[ ${ANSWERS[hostname]:-} == aurade ]] ||
  fail 'the last line of a file with no trailing newline was dropped'

: >"$TMP/empty"
loaded "$TMP/empty" || fail 'an empty file was refused'
(( ${#ANSWERS[@]} == 0 )) || fail 'an empty file filled something in'

# --- files that are not files ------------------------------------------------
#
# `-r` is true of a directory, and true of nearly everything when the installer
# is running as root, which it always is. So `-r` alone was never the question.
# `read` on a directory fails without assigning the variable the loop condition
# then reads, and `set -u` turns that into a dead installer rather than a
# refused file. This is one mistyped path: `--answers /mnt/usb`.
install -d "$TMP/a-directory"
rc=0; load "$TMP/a-directory" || rc=$?
(( rc == 1 )) || fail "a directory as the answer file gave exit $rc, not a refusal"

if [[ -e /dev/null ]]; then
  rc=0; load /dev/null || rc=$?
  (( rc == 1 )) || fail "a device node as the answer file gave exit $rc, not a refusal"
fi

rc=0; load "$TMP/not-there" || rc=$?
(( rc == 1 )) || fail "a missing file gave exit $rc, not a refusal"

# --- what an editor puts in front of the first line --------------------------
#
# Notepad, and Visual Studio Code with the box unticked, write a byte order
# mark. Nothing in the file looks wrong, and the answer on line one silently
# stops being an answer. The name reported back is the real name with three
# invisible bytes in front of it, so the screen says `hostname` was not
# supplied while the file plainly says `hostname=aurade`. Evidence that looks
# correct is worse than no evidence.
printf '\xef\xbb\xbfhostname=aurade\nlocale=en_US.UTF-8\n' >"$TMP/bom"
loaded "$TMP/bom" || fail 'a file with a byte order mark was refused'
[[ ${ANSWERS[hostname]:-} == aurade ]] ||
  fail 'a byte order mark ate the first answer in the file'
(( ${#ANSWERS_REJECTED[@]} == 0 )) ||
  fail "a byte order mark was reported as a refused answer: ${ANSWERS_REJECTED[*]}"

# One only, and only on the first line. A mark in the middle of a file is not a
# mark, it is a broken file, and swallowing it there would hide a concatenation
# of two files that needs to be seen.
printf 'hostname=aurade\n\xef\xbb\xbflocale=en_US.UTF-8\n' >"$TMP/inner-bom"
loaded "$TMP/inner-bom" || fail 'a file with a mark on line two was refused'
[[ -z ${ANSWERS[locale]:-} ]] ||
  fail 'a byte order mark in the middle of a file was swallowed'

printf 'hostname=aurade\r\nlocale=en_US.UTF-8\r\n' >"$TMP/crlf"
loaded "$TMP/crlf" || fail 'a file with Windows line endings was refused'
[[ ${ANSWERS[hostname]:-} == aurade ]] || fail 'a carriage return ate an answer'

# --- a name is trimmed, never squeezed ---------------------------------------
#
# The comment above this code always said "trailing and leading spaces around
# the name only". The code deleted every space in the name, which is a
# different thing, and the difference is that `t a r g e t=/dev/sda` chose a
# disk to erase.
printf '%s\n' 't a r g e t=/dev/sda' >"$TMP/squeezed"
loaded "$TMP/squeezed" || fail 'a file with a spaced out name was refused'
[[ -z ${ANSWERS[target]:-} ]] ||
  fail 'a name with spaces inside it was squeezed into a real question and set the disk to erase'
[[ " ${ANSWERS_REJECTED[*]} " == *' t a r g e t '* ]] ||
  fail 'a name with spaces inside it was dropped without being reported'

printf '%s\n' '  hostname  =aurade' >"$TMP/padded"
loaded "$TMP/padded" || fail 'a file with a padded name was refused'
[[ ${ANSWERS[hostname]:-} == aurade ]] ||
  fail 'spaces around a name stopped it being that name'

# The value is not trimmed, and that is on purpose: a device path or a locale
# that lost a character to tidying would be a different answer that still
# passes its validator. So a padded value is refused and reported, not quietly
# repaired into something the file did not say.
for pad in ' aurade ' ' aurade' 'aurade '; do
  printf '%s\n' "hostname=$pad" >"$TMP/padded-value"
  loaded "$TMP/padded-value" || fail "a file with the value '$pad' was refused"
  [[ -z ${ANSWERS[hostname]:-} ]] ||
    fail "the value '$pad' was silently trimmed into '${ANSWERS[hostname]}'"
  [[ " ${ANSWERS_REJECTED[*]} " == *' hostname '* ]] ||
    fail "the value '$pad' was dropped without being reported"
done

# --- what a name may carry onto a screen -------------------------------------
#
# A name out of this file goes onto the review screen, and the review screen is
# the one before the erase gate. `\e[2J` clears a terminal, `\e[?1049h`
# replaces it, and `\e[10A` moves the cursor up over what is already drawn. A
# file that can do any of those to the screen before the gate is a file that
# can make the gate appear to say something else.
printf 'ho\033[2Jst\033[?1049hname=aurade\n' >"$TMP/escapes"
loaded "$TMP/escapes" || fail 'a file with escapes in a name was refused'
printf '%s' "${ANSWERS_REJECTED[*]-}" >"$TMP/reported"
refute grep -qP '\x1b' "$TMP/reported"
refute grep -qP '[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]' "$TMP/reported"

# A name that is nothing but control characters sanitises to an empty string,
# which is not a name, and is also the fatal empty subscript again by another
# route. It is counted rather than named.
printf '\001\002\003=x\n' >"$TMP/control-only"
survives 'a name made only of control characters' "$TMP/control-only"
loaded "$TMP/control-only"
(( ${#ANSWERS_REJECTED[@]} == 0 )) ||
  fail 'a name made only of control characters was listed as a name'
(( ANSWERS_REJECTED_MORE == 1 )) ||
  fail 'a name made only of control characters was not counted'

# --- what a name may do to the size of a screen ------------------------------
#
# Three hundred thousand bytes on one line is legal in a text file. Wrapped
# into the frame at sixty-eight columns that is four thousand rows of warning,
# and the review screen is somewhere underneath it.
{ head -c 300000 /dev/zero | tr '\0' 'k'; printf '=x\n'; } >"$TMP/long-name"
loaded "$TMP/long-name" || fail 'a file with a very long name was refused'
(( ${#ANSWERS_REJECTED[0]} <= ANSWERS_REJECT_WIDTH + 3 )) ||
  fail "a ${#ANSWERS_REJECTED[0]} character name reached the screen whole"
[[ ${ANSWERS_REJECTED[0]} == *... ]] ||
  fail 'a truncated name does not say that it was truncated'

for i in $(seq 1 500); do printf 'nosuch%s=x\n' "$i"; done >"$TMP/many-names"
loaded "$TMP/many-names" || fail 'a file with five hundred bad names was refused'
(( ${#ANSWERS_REJECTED[@]} == ANSWERS_REJECT_MAX )) ||
  fail "${#ANSWERS_REJECTED[@]} names reached the screen, not $ANSWERS_REJECT_MAX"
(( ANSWERS_REJECTED_MORE == 500 - ANSWERS_REJECT_MAX )) ||
  fail "the count of the rest is $ANSWERS_REJECTED_MORE, not $(( 500 - ANSWERS_REJECT_MAX ))"

# And the screen says the count out loud rather than showing eight names and
# implying that was all of them.
review_list 0 >"$TMP/review.out" 2>&1 || true
grep -Fq 'and 492 more' "$TMP/review.out" ||
  fail 'the review screen showed the first few refused names and not the count'

# --- a value is bytes, and long ones are the validator's problem -------------
{ printf 'hostname='; head -c 200000 /dev/zero | tr '\0' 'a'; printf '\n'; } >"$TMP/long-value"
loaded "$TMP/long-value" || fail 'a file with a very long value was refused'
[[ -z ${ANSWERS[hostname]:-} ]] ||
  fail 'a two hundred thousand character hostname was accepted'

printf '%s\n' 'locale=en_US.UTF-8=extra' >"$TMP/two-equals"
loaded "$TMP/two-equals" || fail 'a file with two equals signs was refused'
[[ -z ${ANSWERS[locale]:-} ]] ||
  fail 'a value with an equals sign in it was accepted without its validator saying so'

# Shell metacharacters in a value are text. This has never gone wrong, and the
# reason to assert it is that the value ends up on an argument list to a
# destructive engine, so "has never gone wrong" is not the standard.
printf '%s\n' 'hostname=$(touch '"$TMP"'/pwned)' 'hostname=`touch '"$TMP"'/pwned2`' \
  'hostname=a;touch '"$TMP"'/pwned3' >"$TMP/injection"
loaded "$TMP/injection" || fail 'a file with shell metacharacters was refused'
refute test -e "$TMP/pwned"
refute test -e "$TMP/pwned2"
refute test -e "$TMP/pwned3"
[[ -z ${ANSWERS[hostname]:-} ]] ||
  fail 'a hostname made of shell metacharacters passed its validator'

# A name that is a glob is a name, not a pattern. `*=x` in a directory full of
# files must not become the name of whatever is in that directory.
cd "$TMP"
printf '%s\n' '*=x' 'host*=y' >"$TMP/globs"
loaded "$TMP/globs" || fail 'a file with glob names was refused'
[[ " ${ANSWERS_REJECTED[*]} " == *' * '* ]] ||
  fail "a glob name was expanded rather than reported: ${ANSWERS_REJECTED[*]}"
cd "$ROOT"

# --- the same file twice ------------------------------------------------------
#
# Loading twice must leave the same state, because the review screen can go
# back to the file and because a second load that adds to the first list would
# report a name that is already filled in.
printf '%s\n' 'hostname=aurade' 'nosuchquestion=x' >"$TMP/twice"
loaded "$TMP/twice" || fail 'the first load was refused'
first=${ANSWERS_REJECTED[*]}
loaded "$TMP/twice" || fail 'the second load was refused'
[[ ${ANSWERS_REJECTED[*]} == "$first" ]] ||
  fail 'loading the same file twice reported a different list the second time'

# --- the last line wins, and a bad line does not undo a good one -------------
printf '%s\n' 'hostname=first-name' 'hostname=second-name' >"$TMP/dupes"
loaded "$TMP/dupes" || fail 'a file with a repeated question was refused'
[[ ${ANSWERS[hostname]:-} == second-name ]] ||
  fail 'the last answer for a question did not win'

printf '%s\n' 'hostname=good-name' 'hostname=-not-a-hostname-' >"$TMP/good-then-bad"
loaded "$TMP/good-then-bad" || fail 'a file with a good line and a bad one was refused'
[[ ${ANSWERS[hostname]:-} == good-name ]] ||
  fail 'a refused line erased the answer a good line had already given'
[[ " ${ANSWERS_REJECTED[*]} " != *' hostname '* ]] ||
  fail 'a question that was answered earlier in the file was reported as missing'

echo 'answer file fuzz test: PASS'
