"""Turn Files' dialogs into the table this page is measured against.

Every dialog Files shows is a `ContentDialog` in `src/Files.App/Dialogs`,
and the things a person reads on one are its title, the text on its buttons
and the captions inside it. Reading the markup gives all three with nothing
retyped in between.

    python3 tools/extract_dialogs.py            # writes assets/files-dialogs.json
    python3 tools/extract_dialogs.py --check    # says whether it is current
"""

import json
import os
import re
import sys
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
PROTO = os.path.dirname(HERE)
REF = os.environ.get("FILES_REF", os.path.join(PROTO, "ref-files"))
DIALOGS = os.path.join(REF, "src/Files.App/Dialogs")
RESW = os.path.join(REF, "src/Files.App/Strings/en-US/Resources.resw")
OUT = os.path.join(PROTO, "assets", "files-dialogs.json")

#: The three buttons a ContentDialog can have, in the order it draws them.
BUTTONS = ("PrimaryButtonText", "SecondaryButtonText", "CloseButtonText")

#: An attribute inside the dialog whose value a person reads.
CAPTION_ATTRS = ("Text", "Header", "Content", "PlaceholderText", "Description")

RESOURCE = re.compile(r"\{helpers:ResourceString\s+Name=([^},\s]+)")

WORDS = None


def strings():
    out = {}
    for data in ET.parse(RESW).getroot().findall("data"):
        name, value = data.get("name"), data.findtext("value")
        if name and value is not None:
            out[name] = value
    return out


def spoken(raw):
    found = RESOURCE.search(raw or "")
    if not found:
        return None
    key = found.group(1).replace("/", ".")
    return WORDS.get(key) or WORDS.get(key.replace(".", "_")) or key


def collect():
    global WORDS
    WORDS = strings()
    out = {}
    for name in sorted(os.listdir(DIALOGS)):
        if not name.endswith(".xaml"):
            continue
        root = ET.parse(os.path.join(DIALOGS, name)).getroot()
        stem = name[:-len(".xaml")]
        key = stem[:-len("Dialog")] if stem.endswith("Dialog") else stem
        buttons = []
        for attr in BUTTONS:
            said = spoken(root.get(attr))
            if said:
                buttons.append(said)
        captions = []
        for el in root.iter():
            for attr in CAPTION_ATTRS:
                said = spoken(el.get(attr))
                if said and said not in captions:
                    captions.append(said)
        #: A dialog whose whole content is built in code, like the one Files
        #: reuses for every yes or no question, says nothing here. Kept, so
        #: the list is the list of dialogs rather than the list of dialogs
        #: that happened to be readable.
        out[key.lower()] = {
            "title": spoken(root.get("Title")),
            "buttons": buttons,
            "captions": captions,
        }
    return out


def main():
    table = collect()
    total = sum(len(d["buttons"]) + len(d["captions"]) + (1 if d["title"] else 0)
                for d in table.values())
    payload = {
        "//": "Generated by tools/extract_dialogs.py from the Files"
              " reference. Do not edit: regenerate.",
        "source": "files-community/Files, src/Files.App/Dialogs",
        "dialogs": len(table),
        "count": total,
        "shown": table,
    }
    text = json.dumps(payload, indent=1, ensure_ascii=False) + "\n"

    if "--check" in sys.argv:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current == text:
            print(f"current: {total} captions over {len(table)} dialogs")
            return 0
        print(f"stale: regenerate tools/extract_dialogs.py"
              f" ({total} captions over {len(table)} dialogs)")
        return 1

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w", encoding="utf-8").write(text)
    print(f"{total} captions over {len(table)} dialogs written to"
          f" {os.path.relpath(OUT, PROTO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
