#!/usr/bin/env python3
"""Pull every translatable string out of the greeter into a catalogue template.

`xgettext` is the usual way and it is not assumed to be installed, because
this has to work on the machine that builds the package rather than only on a
developer's. The strings live in one module, wrapped in one call, so finding
them is a walk of the syntax tree rather than a parse of the language.

    aurade-greeter/tools/extract-copy.py            write po/aurade-greeter.pot
    aurade-greeter/tools/extract-copy.py --check    say what is missing, write nothing

The template is committed. That is deliberate: a translator should be able to
start from the repository without a build step, and a diff on it is the
clearest possible review of what changed about the words.
"""
from __future__ import annotations

import argparse
import ast
import datetime as _dt
import io
import os
import sys

HERE = os.path.dirname(os.path.realpath(__file__))
PACKAGE = os.path.normpath(os.path.join(HERE, ".."))
COPY = os.path.join(PACKAGE, "aurade_greeter", "copy.py")

#: And the modules that build phrases of their own.
#:
#: The first version of this read `copy.py` and stopped there, which left the
#: condition names, the compass points, the ultraviolet bands and the keyboard
#: layout names in English forever while the commit message said every word
#: was translatable. A table of words is product copy wherever it lives.
ALSO = tuple(os.path.join(PACKAGE, "aurade_greeter", name) for name in
             ("weather.py", "settings.py", "shade.py", "outlook.py"))
POT = os.path.join(PACKAGE, "po", "aurade-greeter.pot")


def found(path: str = COPY) -> list[tuple[int, str]]:
    """Every string inside a `_()` call, with the line it is on."""
    tree = ast.parse(io.open(path, encoding="utf-8").read())
    out: list[tuple[int, str]] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        if not isinstance(node.func, ast.Name) or node.func.id != "_":
            continue
        if len(node.args) != 1 or not isinstance(node.args[0], ast.Constant):
            continue
        if not isinstance(node.args[0].value, str):
            continue
        out.append((node.lineno, node.args[0].value))
    return out


def bare(path: str = COPY) -> list[tuple[int, str]]:
    """Assignments whose value is a bare string, which is one nobody can translate.

    The whole point of the gate: a string added later without the call around
    it is invisible to every translator and nothing else would notice.
    """
    tree = ast.parse(io.open(path, encoding="utf-8").read())
    out: list[tuple[int, str]] = []
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        if len(node.targets) != 1 or not isinstance(node.targets[0], ast.Name):
            continue
        name = node.targets[0].id
        # The plumbing at the top of the file is not product copy.
        if name in ("DOMAIN", "LOCALEDIR"):
            continue
        value = node.value
        if isinstance(value, ast.Constant) and isinstance(value.value, str):
            out.append((node.lineno, name))
    return out


def escaped(text: str) -> str:
    return (text.replace("\\", "\\\\").replace('"', '\\"')
                .replace("\n", "\\n").replace("\t", "\\t"))


def template(strings: list[tuple[int, str]]) -> str:
    stamp = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%d %H:%M+0000")
    lines = [
        "# Translations for the AuraDE greeter.",
        "# This file is generated by tools/extract-copy.py. Do not edit it.",
        "#",
        'msgid ""',
        'msgstr ""',
        '"Project-Id-Version: aurade-greeter\\n"',
        f'"POT-Creation-Date: {stamp}\\n"',
        '"MIME-Version: 1.0\\n"',
        '"Content-Type: text/plain; charset=UTF-8\\n"',
        '"Content-Transfer-Encoding: 8bit\\n"',
        "",
    ]
    seen: set[str] = set()
    for line, text in strings:
        if text in seen:
            continue
        seen.add(text)
        lines.append(f"#: aurade_greeter/copy.py:{line}")
        lines.append(f'msgid "{escaped(text)}"')
        lines.append('msgstr ""')
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="report drift and write nothing")
    args = parser.parse_args()

    strings = found()
    for extra in ALSO:
        if os.path.isfile(extra):
            name = os.path.relpath(extra, PACKAGE)
            strings += [(line, text) for line, text in found(extra)]
    missing = bare()
    if missing:
        for line, name in missing:
            print(f"copy.py:{line}: {name} is not translatable", file=sys.stderr)
        print(f"{len(missing)} string(s) outside a translation call",
              file=sys.stderr)
        return 1

    wanted = template(strings)
    if args.check:
        try:
            have = io.open(POT, encoding="utf-8").read()
        except OSError:
            print("the catalogue template has never been written",
                  file=sys.stderr)
            return 1
        # The timestamp changes on every run and means nothing to a reader.
        strip = lambda t: "\n".join(l for l in t.splitlines()
                                    if not l.startswith('"POT-Creation-Date'))
        if strip(have) != strip(wanted):
            print("the catalogue template is out of date, rerun without "
                  "--check", file=sys.stderr)
            return 1
        print(f"extract-copy: {len(strings)} strings, template current")
        return 0

    os.makedirs(os.path.dirname(POT), exist_ok=True)
    io.open(POT, "w", encoding="utf-8").write(wanted)
    print(f"extract-copy: {len(strings)} strings written to "
          f"{os.path.relpath(POT, PACKAGE)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
