"""Generated by installer/tools/generate-theme.py. Do not edit by hand.

The same Material 3 roles the stylesheet defines, for the parts of the
interface that are drawn rather than styled. Cairo cannot read GTK CSS,
so the aurora, the signal arcs and the stage timeline read their colours
from here and stay in step with everything else by construction.
"""

from __future__ import annotations

BRAND_HUES = {'lilac': 298.618, 'aqua': 226.590, 'plate': 274.237}

PALETTES = {
    'primary': {0: '#000000', 4: '#180033', 6: '#1f003f', 10: '#2a0053', 12: '#2e0558', 17: '#381564', 20: '#3f1d6c', 22: '#432271', 24: '#482776', 30: '#553586', 40: '#6d4ea1', 50: '#8567bd', 60: '#9f81d9', 70: '#ba9cf6', 80: '#d1bcff', 87: '#e0d4ff', 90: '#e7deff', 92: '#ece4ff', 94: '#f0ebfe', 95: '#f3eeff', 96: '#f5f2ff', 98: '#faf8fe', 99: '#fdfcff', 100: '#ffffff'},
    'secondary': {0: '#000000', 4: '#090c22', 6: '#0e1228', 10: '#161a31', 12: '#1a1e35', 17: '#242941', 20: '#2a2f48', 22: '#2e334c', 24: '#323851', 30: '#404660', 40: '#575d79', 50: '#6f7693', 60: '#8890ad', 70: '#a3aac9', 80: '#bec5e5', 87: '#d1d9f9', 90: '#dae2fe', 92: '#e2e8fe', 94: '#e9edfe', 95: '#edf0fe', 96: '#f0f3fe', 98: '#f8f9fe', 99: '#fbfcfe', 100: '#ffffff'},
    'tertiary': {0: '#000000', 4: '#001018', 6: '#00161f', 10: '#011f2a', 12: '#01232f', 17: '#012e3d', 20: '#033545', 22: '#023a4c', 24: '#013e52', 30: '#014d64', 40: '#156682', 50: '#357f9c', 60: '#519ab7', 70: '#6cb5d3', 80: '#87d0ef', 87: '#a3e3ff', 90: '#baeaff', 92: '#c9eeff', 94: '#d7f2fe', 95: '#def4fe', 96: '#e5f6fe', 98: '#f2fbff', 99: '#f9fdff', 100: '#ffffff'},
    'neutral': {0: '#000000', 4: '#0d0e13', 6: '#121318', 10: '#1a1b20', 12: '#1e1f25', 17: '#282a2f', 20: '#2f3036', 22: '#33353a', 24: '#37393f', 30: '#45474c', 40: '#5c5e64', 50: '#75777d', 60: '#8f9097', 70: '#a9abb2', 80: '#c4c6cd', 87: '#d8dae1', 90: '#e0e2e9', 92: '#e6e8ef', 94: '#eceef5', 95: '#eff0f8', 96: '#f1f3fb', 98: '#f8f9ff', 99: '#fbfcff', 100: '#ffffff'},
    'neutral_variant': {0: '#000000', 4: '#0b0e18', 6: '#10131d', 10: '#181b26', 12: '#1c1f2a', 17: '#272935', 20: '#2d303c', 22: '#313440', 24: '#363945', 30: '#434653', 40: '#5a5e6b', 50: '#737785', 60: '#8c909f', 70: '#a7abba', 80: '#c2c6d5', 87: '#d5dae9', 90: '#dee2f2', 92: '#e4e8f8', 94: '#e9edfd', 95: '#ecf0ff', 96: '#f0f3ff', 98: '#f8f9ff', 99: '#fbfcff', 100: '#ffffff'},
    'error': {0: '#000000', 4: '#270001', 6: '#310001', 10: '#410002', 12: '#480103', 17: '#5c0004', 20: '#680106', 22: '#710107', 24: '#790209', 30: '#93000c', 40: '#b12c28', 50: '#cf4942', 60: '#ed655b', 70: '#ff8a7e', 80: '#feb4ab', 87: '#fecfc9', 90: '#fedbd6', 92: '#fee2de', 94: '#ffe9e6', 95: '#ffedea', 96: '#fff0ee', 98: '#fef8f7', 99: '#fefcfb', 100: '#ffffff'},
}

LIGHT = {
    'primary': '#6d4ea1',
    'on_primary': '#ffffff',
    'primary_container': '#e7deff',
    'on_primary_container': '#2a0053',
    'secondary': '#575d79',
    'on_secondary': '#ffffff',
    'secondary_container': '#dae2fe',
    'on_secondary_container': '#161a31',
    'tertiary': '#156682',
    'on_tertiary': '#ffffff',
    'tertiary_container': '#baeaff',
    'on_tertiary_container': '#011f2a',
    'error': '#b12c28',
    'on_error': '#ffffff',
    'error_container': '#fedbd6',
    'on_error_container': '#410002',
    'surface': '#f8f9ff',
    'on_surface': '#1a1b20',
    'surface_dim': '#d8dae1',
    'surface_bright': '#f8f9ff',
    'surface_container_lowest': '#ffffff',
    'surface_container_low': '#f1f3fb',
    'surface_container': '#eceef5',
    'surface_container_high': '#e6e8ef',
    'surface_container_highest': '#e0e2e9',
    'surface_variant': '#dee2f2',
    'on_surface_variant': '#434653',
    'outline': '#737785',
    'outline_variant': '#c2c6d5',
    'inverse_surface': '#2f3036',
    'inverse_on_surface': '#eff0f8',
    'inverse_primary': '#d1bcff',
    'scrim': '#000000',
    'shadow': '#000000',
}

DARK = {
    'primary': '#d1bcff',
    'on_primary': '#3f1d6c',
    'primary_container': '#553586',
    'on_primary_container': '#e7deff',
    'secondary': '#bec5e5',
    'on_secondary': '#2a2f48',
    'secondary_container': '#404660',
    'on_secondary_container': '#dae2fe',
    'tertiary': '#87d0ef',
    'on_tertiary': '#033545',
    'tertiary_container': '#014d64',
    'on_tertiary_container': '#baeaff',
    'error': '#feb4ab',
    'on_error': '#680106',
    'error_container': '#93000c',
    'on_error_container': '#fedbd6',
    'surface': '#121318',
    'on_surface': '#e0e2e9',
    'surface_dim': '#121318',
    'surface_bright': '#37393f',
    'surface_container_lowest': '#0d0e13',
    'surface_container_low': '#1a1b20',
    'surface_container': '#1e1f25',
    'surface_container_high': '#282a2f',
    'surface_container_highest': '#33353a',
    'surface_variant': '#434653',
    'on_surface_variant': '#c2c6d5',
    'outline': '#8c909f',
    'outline_variant': '#434653',
    'inverse_surface': '#e0e2e9',
    'inverse_on_surface': '#2f3036',
    'inverse_primary': '#6d4ea1',
    'scrim': '#000000',
    'shadow': '#000000',
}

SHAPE = {'none': 0, 'xs': 4, 'sm': 8, 'md': 12, 'lg': 16, 'xl': 28, 'full': 999}
STATE = {'hover': 0.08, 'focus': 0.1, 'pressed': 0.1, 'dragged': 0.16, 'disabled_content': 0.38, 'disabled_container': 0.12}
TYPE = {'display_large': (57, 400, -0.25, 64), 'display_medium': (45, 400, 0.0, 52), 'display_small': (36, 400, 0.0, 44), 'headline_large': (32, 400, 0.0, 40), 'headline_medium': (28, 400, 0.0, 36), 'headline_small': (24, 400, 0.0, 32), 'title_large': (22, 400, 0.0, 28), 'title_medium': (16, 500, 0.15, 24), 'title_small': (14, 500, 0.1, 20), 'body_large': (16, 400, 0.5, 24), 'body_medium': (14, 400, 0.25, 20), 'body_small': (12, 400, 0.4, 16), 'label_large': (14, 500, 0.1, 20), 'label_medium': (12, 500, 0.5, 16), 'label_small': (11, 500, 0.5, 16)}


def scheme(dark: bool) -> dict[str, str]:
    """The role table for the scheme currently in use."""
    return DARK if dark else LIGHT


def rgb(value: str) -> tuple[float, float, float]:
    """A role colour as Cairo wants it."""
    return tuple(int(value[i:i + 2], 16) / 255 for i in (1, 3, 5))
