[options]
HoldPkg = pacman glibc
Architecture = auto
CheckSpace
ParallelDownloads = 5
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Server = https://archive.archlinux.org/repos/__AURADE_ARCH_SNAPSHOT__/$repo/os/$arch

[extra]
Server = https://archive.archlinux.org/repos/__AURADE_ARCH_SNAPSHOT__/$repo/os/$arch
