#!/usr/bin/env bash
# Export self-contained directories suitable for separate AUR package repos.
#
# The source tree is intentionally a monorepo, while the AUR expects one Git
# repository per package. This exporter copies only package inputs and emits
# a small x86_64 -bin wrapper for the currently published Chromium payload.
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
WORKDIR="${AURADE_WORKDIR:-${REPO_ROOT}/.aurade-work}"
OUTPUT="${AURADE_AUR_OUTPUT:-${WORKDIR}/aur-bundles}"
RELEASE_TAG="${AURADE_AUR_RELEASE_TAG:-v0.1.0-prealpha}"
RELEASE_ARCHIVE="${AURADE_AUR_RELEASE_ARCHIVE:-aurade-v0.1.0-prealpha-x86_64-repository.tar.gz}"
RELEASE_SHA256="${AURADE_AUR_ARCHIVE_SHA256:-87289829d7c1a99c29f50a21bc3c41a275c7793f7483c029e930da593bdd7ff0}"
CHROMIUM_VERSION="${AURADE_AUR_CHROMIUM_VERSION:-152.1660893}"
CHROMIUM_PKGREL="${AURADE_AUR_CHROMIUM_PKGREL:-4}"

SOURCE_PACKAGES=(
  aurade-account-helper
  aurade-system-helper
  shill-nm-adapter
  aurade-power
  aurade-host-bridge
  aurade-login
  aurade-ai
  aurade-webapp-shortcuts
  aurade
  aurade-full
)

die() {
  printf 'export-aur-bundles: %s\n' "$*" >&2
  exit 1
}

[[ "${OUTPUT}" = /* && "${OUTPUT}" != / ]] ||
  die 'AURADE_AUR_OUTPUT must be an absolute, non-root path'
[[ "${RELEASE_TAG}" =~ ^[A-Za-z0-9._/-]+$ ]] ||
  die 'AURADE_AUR_RELEASE_TAG contains unsupported characters'
[[ "${RELEASE_ARCHIVE}" =~ ^[A-Za-z0-9._-]+$ ]] ||
  die 'AURADE_AUR_RELEASE_ARCHIVE contains unsupported characters'
[[ "${RELEASE_SHA256}" =~ ^[[:xdigit:]]{64}$ ]] ||
  die 'AURADE_AUR_ARCHIVE_SHA256 must be a 64-character hex digest'
[[ "${CHROMIUM_VERSION}" =~ ^[0-9]+([.][0-9]+)*$ ]] ||
  die 'AURADE_AUR_CHROMIUM_VERSION must be a numeric package version'
[[ "${CHROMIUM_PKGREL}" =~ ^[0-9]+$ ]] ||
  die 'AURADE_AUR_CHROMIUM_PKGREL must be numeric'
[[ ! -e "${OUTPUT}" ]] ||
  die "output already exists; choose another path or remove it first: ${OUTPUT}"

mkdir -p "${OUTPUT}"

copy_package() {
  local package="$1"
  local package_dir="${OUTPUT}/${package}"
  [[ -f "${REPO_ROOT}/${package}/PKGBUILD" ]] ||
    die "missing package directory: ${package}"
  mkdir -p "${package_dir}"
  cp -a "${REPO_ROOT}/${package}/." "${package_dir}/"

  # AUR helpers resolve dependency names before installing packages. Point
  # the generated meta/session helpers at the explicit -bin provider rather
  # than relying on a virtual provide that an AUR helper may not discover.
  case "${package}" in
    aurade)
      sed -i 's/chromiumos-ash>=/chromiumos-ash-bin>=/' \
        "${package_dir}/PKGBUILD"
      rm -f "${package_dir}/.SRCINFO"
      ;;
    aurade-login|aurade-webapp-shortcuts)
      sed -i "s/'chromiumos-ash'/'chromiumos-ash-bin'/g" \
        "${package_dir}/PKGBUILD"
      rm -f "${package_dir}/.SRCINFO"
      ;;
  esac

  find "${package_dir}" -type f -size +50M -print -quit | {
    read -r oversized || true
    [[ -z "${oversized}" ]] || die "unexpected oversized AUR input: ${oversized}"
  }
}

for package in "${SOURCE_PACKAGES[@]}"; do
  copy_package "${package}"
done

release_archive_template="${RELEASE_ARCHIVE//x86_64/\$CARCH}"
release_url_template="https://github.com/Cam396/aurade/releases/download/${RELEASE_TAG}/${release_archive_template}"
mkdir -p "${OUTPUT}/chromiumos-ash-bin"
cat >"${OUTPUT}/chromiumos-ash-bin/PKGBUILD" <<EOF
# Maintainer: AuraDE Contributors
# Generated by ci/export-aur-bundles.sh. This is the x86_64 binary AUR path.
pkgname=chromiumos-ash-bin
pkgver=${CHROMIUM_VERSION}
pkgrel=${CHROMIUM_PKGREL}
pkgdesc="Prebuilt ChromeOS Ash desktop environment for Linux (AuraDE development build)"
arch=('x86_64')
url="https://github.com/Cam396/aurade"
license=('BSD-3-Clause')
depends=(
    'shill-nm-adapter'
    'bash'
    'dbus'
    'dbus-glib'
    'util-linux'
    'python'
    'python-dbus'
    'python-gobject'
    'libgl'
    'wayland'
    'weston'
    'seatd'
    'xorg-xwayland'
    'libxkbcommon'
    'libx11'
    'libxcb'
    'libxcomposite'
    'libxdamage'
    'libxext'
    'libxfixes'
    'libxi'
    'libxrandr'
    'libxrender'
    'libxss'
    'libxtst'
    'pango'
    'cairo'
    'nss'
    'nspr'
    'alsa-lib'
    'pipewire'
    'minizip'
    'libevent'
    'libdrm'
    'mesa'
    'hwdata'
    'harfbuzz'
    'freetype2'
    'ttf-roboto'
    'libpng'
    'libjpeg-turbo'
    'tar'
    'gzip'
    'bzip2'
    'xz'
    'zstd'
    'lzip'
    '7zip'
    'unrar'
    'aurade-system-helper'
    'aurade-account-helper'
    'polkit'
    'pam'
    'shadow'
    'accountsservice'
)
optdepends=(
    'lm_sensors: userspace sensor discovery and setup tools for host hwmon devices'
    'vulkan-driver: hardware Vulkan acceleration when supported by the GPU'
    'mesa-utils: GPU smoke-test tools such as glxinfo and eglinfo'
    'aurade-ai: Advanced Plus AI local Gemma model bootstrap'
    'aurade-login: PAM greeter, lock screen, and logind session controls'
    'aurade-power: event-driven Linux laptop suspend and power lifecycle bridge'
    'aurade-host-bridge: BlueZ, udisks2, MIME, and pacman host integration'
    'udiskie: opt-in recovery automounter when AURADE_REMOVABLE_AUTOMOUNT=1'
)
provides=("chromiumos-ash=\${pkgver}-\${pkgrel}")
conflicts=('chromiumos-ash')
source=("aurade-repository.tar.gz::${release_url_template}")
sha256sums=('${RELEASE_SHA256}')

package() {
    local payload="\${srcdir}/repository/chromiumos-ash-\${pkgver}-\${pkgrel}-\${CARCH}.pkg.tar.gz"
    [[ -f "\${payload}" ]] || {
        printf 'missing Chromium payload in release archive: %s\\n' "\${payload}" >&2
        return 1
    }
    bsdtar --exclude='.BUILDINFO' --exclude='.MTREE' --exclude='.PKGINFO' \\
        -xpf "\${payload}" -C "\${pkgdir}"
}
EOF

commit="$(git -C "${REPO_ROOT}" rev-parse --short=12 HEAD 2>/dev/null || printf unknown)"
cat >"${OUTPUT}/AUR-EXPORT.md" <<EOF
# AuraDE AUR export

Generated from AuraDE commit ${commit}.

The directories below are intentionally self-contained because the AUR uses
one Git repository per package. Upload each package directory to its own AUR
repository only after the current VM/hardware feedback is accepted.

The chromiumos-ash-bin package is the current x86_64 development path. It
downloads the unsigned Chromium payload from the GitHub release
${RELEASE_TAG} and verifies SHA-256 ${RELEASE_SHA256}. It provides
chromiumos-ash for manual installs; generated AUR meta/session packages use
the explicit chromiumos-ash-bin dependency so AUR helpers resolve it.
There is no ARM binary claim.

Before upload, run makepkg --printsrcinfo as an unprivileged Arch user,
namcap PKGBUILD, and makepkg --verifysource in every directory.
Do not upload the parent repository, private engineering documents, VM
credentials, build logs, ISO files, or package archives to an AUR package repo.
EOF

printf 'AUR bundles exported to %s\n' "${OUTPUT}"
printf 'Packages: %s plus chromiumos-ash-bin\n' "${#SOURCE_PACKAGES[@]}"
